title: "ComBayNS 2025 Workshop @ IJCNN 2025"
description: "Combining Bayesian and Neural approaches for Structured data"
theme: minima # or any Jekyll theme you like
baseurl: "" # Update if the site is in a subdirectory
url: "https://combayns2025.github.io" # Your GitHub Pages URL


nav:
  - title: Home
    url: /
  - title: Call for papers
    url: /call-for-papers/
  - title: Program
    url: /program/
  # - title: Speakers
  #   url: /speakers/
  # - title: Organizers
  #   url: /organizers/
  # - title: Contacts
  #   url: /contacts/
