title: "ComBayNS 2025 Workshop @ IJCNN 2025"
description: "Combining Bayesian and Neural approaches for Structured data"
theme: minima # or any Jekyll theme you like
baseurl: "" # Update if the site is in a subdirectory
url: "https://yourusername.github.io" # Your GitHub Pages URL
